import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "FinerLux",
  description: "Generated by FinerLux",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* Preload critical images */}
        <link
          rel="preload"
          href="/assets/finerlux-rabbit-full-logo-blue.svg"
          as="image"
        />
        <link rel="preload" href="/assets/hero-watch.webp" as="image" />
        <link rel="preload" href="/assets/mobile.svg" as="image" />
        <link
          rel="preload"
          href="/assets/rolex-daytona-116500ln-panda-cover.webp"
          as="image"
        />
        <link
          rel="preload"
          href="/assets/rolex-gmt-master-2-126720vtnr-sprite-cover.webp"
          as="image"
        />
        <link
          rel="preload"
          href="/assets/rolex-gmt-master-2-126711chnr-rootbeer-cover.webp"
          as="image"
        />
        <link
          rel="preload"
          href="/assets/rolex-gmt-master-2-126710blro-pepsi-cover.webp"
          as="image"
        />
        <link
          rel="preload"
          href="/assets/rolex-gmt-master-2-126710blnr-batgirl-cover.webp"
          as="image"
        />

      </Head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
